
definitions:
  User:
    type: "object"
     properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
        format: "password"
    xml:
      name: "User"

  Album:
    type: "object"
    properties:
      title:
        type: "string"
      author:
        type: "string"
      description:
        type: "string"
      published_year:
        type: "string"
      publisher:
        type: "string"
      genre:
        type: "string"
      updated_date:
        type: "string"
        format: "date"
    xml:
      name: "Album"

  Game:
    type: "object"
    properties:
      title:
        type: "string"
      author:
        type: "string"
      description:
        type: "string"
      published_year:
        type: "string"
      publisher:
        type: "string"
      producer:
        type: "string"
      platforms:
        type: "array"
        xml:
          name: "platforms"
        items:
          type: "string"
      updated_date:
        type: "string"
        format: "date"
    xml:
      name: "Album"

  Movies:
    type: "object"
    properties:
      director:
        type: "string"
      title:
        type: "string"
      genre:
        type: "string"
      description:
        type: "string"
      published_year:
        type: "string"
      wrtier:
        type: "string"
      producer:
        type: "string"
      actors:
        type: "array"
        xml:
          name: "actors"
        items:
          type: "string"
      updated_date:
        type: "string"
        format: "date"
    xml:
      name: "Album"

  Series:
    type: "object"
    properties:
      title:
        type: "string"
      author:
        type: "string"
      channel:
        type: "string"
      nb_seasons:
        type: "string"
      description:
        type: "string"
      published_year:
        type: "string"
      published:
        type: "string"
      actors:
        type: "array"
        xml:
          name: "actors"
        items:
          type: "string"
      updated_date:
        type: "string"
        format: "date"
    xml:
      name: "Album"

  Books:
    type: "object"
    properties:
      isbn:
        type: "string"
      title:
        type: "string"
      author:
        type: "string"
      description:
        type: "string"
      published_year:
        type: "string"
      publisher:
        type: "string"
      updated_date:
        type: "string"
        format: "date"
    xml:
      name: "Album"
